Roberto Mendoza Matos 

1. Ejercicio 01

In [2]:
import numpy as np

In [3]:
A = np.array([[6,0,0,0],[6,6,0,0], [6,6,6,0],[6,6,6,6]])
A

array([[6, 0, 0, 0],
       [6, 6, 0, 0],
       [6, 6, 6, 0],
       [6, 6, 6, 6]])

2. Crear un array de 4x4 con valores pares

In [4]:
B = np.array([[2,4,8,12],[4,2,24,28],[102,308,100,50],[38,20,10268,2]])
B

array([[    2,     4,     8,    12],
       [    4,     2,    24,    28],
       [  102,   308,   100,    50],
       [   38,    20, 10268,     2]])

3. Crear un array de 4x3 con valores impares

In [5]:
C = np.array([[1,7,9],[11,17,19],[21,27,29],[31,37,39]])
C

array([[ 1,  7,  9],
       [11, 17, 19],
       [21, 27, 29],
       [31, 37, 39]])

4. Crear un array que contenga 32 elementos y luego darle 4 posibles formas que puede tomar el array creado inicialmente

In [15]:
vector = np.arange(1,65,2)
vector
# dimension
vector.size

vector1 = print(vector.reshape(4,8))
vector1 = print(vector.reshape(16,2))
vector1 = print(vector.reshape(8,4))
#######################################
vector1 = print(vector.reshape(2,4,4))

[[ 1  3  5  7  9 11 13 15]
 [17 19 21 23 25 27 29 31]
 [33 35 37 39 41 43 45 47]
 [49 51 53 55 57 59 61 63]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]
 [21 23]
 [25 27]
 [29 31]
 [33 35]
 [37 39]
 [41 43]
 [45 47]
 [49 51]
 [53 55]
 [57 59]
 [61 63]]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]
 [41 43 45 47]
 [49 51 53 55]
 [57 59 61 63]]
[[[ 1  3  5  7]
  [ 9 11 13 15]
  [17 19 21 23]
  [25 27 29 31]]

 [[33 35 37 39]
  [41 43 45 47]
  [49 51 53 55]
  [57 59 61 63]]]


5. Crear un array de 3x3x3 y ubicar 10 elementos utilizando los metodos de slicing aprendidos en clase

In [87]:
matrix3 = np.arange(26,105,3)
matrix3.size

mat = matrix3.reshape(3,3,3)
mat

mat.shape

mat[1,0:3]
np.array([[mat[[1],[0,0,1,1,2],[0,1,0,1,2]]],[mat[[0],[0,0,1,1,2],[0,1,0,1,2]]]])

array([[[53, 56, 62, 65, 77]],

       [[26, 29, 35, 38, 50]]])

6. Crear el array utilizando los metodos aprendidos en clase

In [117]:
tarea = np.array([[2,2,2,2,2],[2,0,0,0,2],[2,0,16,0,2],[2,0,0,0,2],[2,2,2,2,2]])
tarea

array([[ 2,  2,  2,  2,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  0, 16,  0,  2],
       [ 2,  0,  0,  0,  2],
       [ 2,  2,  2,  2,  2]])

In [115]:
vector1 = np.ones((1,5))*2
vector1

vector2 = np.array([vector1[0,0],0,0,0,vector1[0,0]])
vector2

vector3 = np.array([2,0,16,0,2])
vector3

mat_3 = np.vstack((vector1,vector2,vector3,vector2,vector1))
mat_3

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 2.,  0.,  0.,  0.,  2.],
       [ 2.,  0., 16.,  0.,  2.],
       [ 2.,  0.,  0.,  0.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])